/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (men-in-black-the-game-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80016C4Cu
#define func_80016C4C BootEntry  /* alias */
